#Butmalai Dan 333CC
build: TemaC.l
	flex TemaC.l
	gcc lex.yy.c
run: 
	make build
	./a.out < in1.txt > out1.txt
	./a.out < in2.txt > out2.txt
	./a.out < in3.txt > out3.txt
	./a.out < in4.txt > out4.txt